name: CI

env:
  IMAGE_NAME: ohfreeya/test-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    outputs:
      test-error: ${{ steps.run-test.outputs.error_msg }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        id: run-test
        run: |
          go mod tidy
          if ! go test -v ./... -race -cover 2>&1 | tee test_log.txt; then
            ERROR=$(tail -n 5 test_log.txt | tr -d '"\' | tr '\n' ' ')
            echo "error_msg=Test Error: $ERROR" >> $GITHUB_OUTPUT
            exit 1 
          fi

  build-and-push:
    name: Build Docker Image
    runs-on: ubuntu-latest
    outputs:
      build-error: ${{ steps.build-img.outputs.error_msg }}
      push-error: ${{ steps.push-img.outputs.error_msg }}
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      id: build-img
      run: |
        if ! docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} . 2>&1 | tee build_log.txt; then
          ERROR_MSG=$(tail -n 5 build_log.txt | tr -d '"\' | tr '\n' ' ')
          echo "error_msg=$ERROR_MSG" >> $GITHUB_OUTPUT
          exit 1
        fi
        echo "error_msg=Push error: zac test" >> $GITHUB_OUTPUT
        exit 1

    - name: Push image
      id: push-img
      run: |
        if ! docker push $IMAGE_NAME:latest 2>&1 | tee push_log.txt; then
          ERROR_MSG=$(tail -n 5 push_log.txt | tr -d '"\' | tr '\n' ' ')
          echo "error_msg=$ERROR_MSG" >> $GITHUB_OUTPUT
          exit 1
        fi
        if ! docker push $IMAGE_NAME:${{ github.sha }} 2>&1 | tee push_log.txt; then
          ERROR_MSG=$(tail -n 5 push_log.txt | tr -d '"\' | tr '\n' ' ')
          echo "error_msg=$ERROR_MSG" >> $GITHUB_OUTPUT
          exit 1
        fi

  notify:
    name: Notify Teams
    runs-on: ubuntu-latest
    needs: [test, build-and-push]
    if: always()
    steps:
      - name: Set Status Text
        id: info
        run: |
          TEST_RES="${{ needs.test.result }}"
          BUILD_RES="${{ needs.build-and-push.result }}"
          if [ "$TEST_RES" == "success" ] && [ "$BUILD_RES" == "success" ]; then
            echo "status=Success âœ…" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
            echo "reason=All stages passed successfully." >> $GITHUB_OUTPUT
          elif [ "$TEST_RES" == "failure" ]; then
            T_ERR="${{ needs.test.outputs.test-error }}"
            echo "status=Failed âŒ" >> $GITHUB_OUTPUT
            echo "color=attention" >> $GITHUB_OUTPUT
            echo "reason=$T_ERR" >> $GITHUB_OUTPUT
          else
            B_ERR="${{ needs.build-and-push.outputs.build-error }}"
            P_ERR="${{ needs.build-and-push.outputs.push-error }}"
            FINAL_ERR="${B_ERR:-$P_ERR}"
            echo "status=Failed âŒ" >> $GITHUB_OUTPUT
            echo "color=attention" >> $GITHUB_OUTPUT
            echo "reason=$FINAL_ERR" >> $GITHUB_OUTPUT
          fi

      - name: Notify Teams
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "type": "message",
              "attachments": [{
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    { "type": "TextBlock", "text": "ðŸš€ CI Notification", "weight": "Bolder", "size": "Large" },
                    { "type": "TextBlock", "text": "Result: ${{ steps.info.outputs.status }}", "color": "${{ steps.info.outputs.color }}", "weight": "Bolder" },
                    { "type": "FactSet", "facts": [
                      { "title": "Failure Reason:", "value": "${{ steps.info.outputs.reason }}" },
                      { "title": "Repository:", "value": "${{ github.repository }}" },
                      { "title": "Commit:", "value": "${{ github.sha }}" }
                    ]},
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.4"
                }
              }]
            }' "${{ secrets.TEAMS_WEBHOOK }}"
