name: CI

env:
  IMAGE_NAME: ohfreeya/test-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Test
        run: |
          go mod tidy
          go test -v ./... -race -cover

  build-and-push:
      name: Build Docker Image
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

  notify:
    name: Notify Teams
    runs-on: ubuntu-latest
    needs: [test, build-and-push]
    if: always()
    steps:
      - name: Set Status Text
        id: info
        run: |
          TEST_RES="${{ needs.test.result }}"
          BUILD_RES="${{ needs.build-and-push.result }}"
          if [ "$TEST_RES" == "success" ] && [ "$BUILD_RES" == "success" ]; then
            echo "status=Success âœ…" >> $GITHUB_OUTPUT
            echo "color=good" >> $GITHUB_OUTPUT
            echo "reason=All stages passed successfully." >> $GITHUB_OUTPUT
          elif [ "$TEST_RES" == "failure" ]; then
            echo "status=Failed âŒ" >> $GITHUB_OUTPUT
            echo "color=attention" >> $GITHUB_OUTPUT
            echo "reason=Tests failed. Please check the test logs." >> $GITHUB_OUTPUT
          else
            echo "status=Failed âŒ" >> $GITHUB_OUTPUT
            echo "color=attention" >> $GITHUB_OUTPUT
            echo "reason=Docker Build or Push to ACR failed." >> $GITHUB_OUTPUT
          fi

      - name: Notify Teams
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "type": "message",
              "attachments": [{
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    { "type": "TextBlock", "text": "ðŸš€ CI Notification", "weight": "Bolder", "size": "Large" },
                    { "type": "TextBlock", "text": "Result: ${{ steps.info.outputs.status }}", "color": "${{ steps.info.outputs.color }}", "weight": "Bolder" },
                    { "type": "FactSet", "facts": [
                      { "title": "Failure Reason:", "value": "${{ steps.info.outputs.reason }}" },
                      { "title": "Repository:", "value": "${{ github.repository }}" },
                      { "title": "Commit:", "value": "${{ github.sha }}" }
                    ]},
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.4"
                }
              }]
            }' "${{ secrets.TEAMS_WEBHOOK }}"
